CREATE TABLE TS03_01.DEPARTMENTS1 (
    DEPARTMENT_ID1     NUMBER(10) NOT NULL,
    DEPARTMENT_NAME1   VARCHAR2(50) NOT NULL
);

CREATE TABLE TS03_01.DEPARTMENTS2 (
    DEPARTMENT_ID2     NUMBER(10) NOT NULL,
    DEPARTMENT_NAME2   VARCHAR2(50) NOT NULL
);

CREATE TABLE TS03_01.DEPARTMENTS3 (
    DEPARTMENT_ID3     NUMBER(10) NOT NULL,
    DEPARTMENT_NAME3  VARCHAR2(50) NOT NULL
);

CREATE TABLE TS03_01.DEPARTMENTS4 (
    DEPARTMENT_ID4     NUMBER(10) NOT NULL,
    DEPARTMENT_NAME4   VARCHAR2(50) NOT NULL
);

DROP TABLE TS03_01.DEPARTMENTS2;
