CREATE TABLE TS24_01.SUPPLIERS
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS24_01.ORDERS
(
ORDER_NUMBER NUMBER(10),
SUPPLIER_ID NUMBER(10),
CITY VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS24_01.CREATE_TAB_SUP_ORD 
IS
BEGIN

CREATE TABLE TS24_01.SUP_ORD AS SELECT SUPPLIERS.SUPPLIER_ID, SUPPLIERS.SUPPLIER_NAME, ORDERS.ORDER_NUMBER  
FROM TS24_01.SUPPLIERS,TS24_01.ORDERS WHERE SUPPLIERS.SUPPLIER_ID = ORDERS.SUPPLIER_ID;

END;
/