CREATE TABLE TS29_01.PART(
PART_NO    NUMBER PRIMARY KEY,
PART_DESC VARCHAR2(200) NOT NULL );
 
CREATE TABLE TS29_01.ITEM (
ITEM_NO   NUMBER,
PART_NO   NUMBER,
ITEM_DESC VARCHAR2(20) NOT NULL,
CONSTRAINT FK_ITEM_PART FOREIGN KEY (PART_NO) REFERENCES TS29_01.PART (PART_NO),
CONSTRAINT PK_ITEM PRIMARY  KEY (ITEM_NO, PART_NO) );