-- PRIMARY KEY CONSTRAINT
CREATE TABLE TS28_01.MY_STATUS1 (
    STATUS_ID       NUMBER PRIMARY KEY,
    PERSON_ID       NUMBER,
    ACTIVE_RECORD   VARCHAR2(1) CHECK (
        UPPER(ACTIVE_RECORD) = 'T'
        OR UPPER(ACTIVE_RECORD) = 'F'
    ),
    PERSON_SSN      VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS28_01.CREATE_TAB_STU2_TS28 
IS
BEGIN

CREATE TABLE TS28_01.MY_STATUS2
    AS
        SELECT
            MS.STATUS_ID,
            MS.PERSON_ID,
            MS.ACTIVE_RECORD,
            MS.PERSON_SSN
        FROM
            TS28_01.MY_STATUS1 MS;
			
			END;
/