CREATE TABLE TS14_01.STUDENTS1 (
    STUDENT_ID     NUMBER(5) NOT NULL,
    STUDENT_NAME   VARCHAR2(20),
    GROUP_ID       FLOAT(5),
    GROUP_ID1      BINARY_FLOAT,
    GROUP_ID2      BINARY_DOUBLE
);

CREATE TABLE TS14_01.STUDENTS2 (
    STUDENT_ID     NUMBER(5) NOT NULL,
    STUDENT_NAME   VARCHAR2(20),
    GROUP_ID       FLOAT(5),
    GROUP_ID1      BINARY_FLOAT,
    GROUP_ID2      BINARY_DOUBLE
);

CREATE MATERIALIZED VIEW TS14_01.M_V_STU_1_2 ON PREBUILT TABLE
    REFRESH
        FAST
        ON COMMIT
ENABLE QUERY REWRITE AS
    SELECT
        S1.STUDENT_ID,
        S1.STUDENT_NAME,
        S2.GROUP_ID,
        S2.GROUP_ID1
    FROM
        TS14_01.STUDENTS1 S1,
        TS14_01.STUDENTS2 S2
    WHERE
        S1.STUDENT_ID = S2.STUDENT_ID;