CREATE TABLE TS21_01.SUPPLIERS
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS21_01.ORDERS
(
ORDER_NUMBER NUMBER(10),
SUPPLIER_ID NUMBER(10),
CITY VARCHAR2(20)
);

CREATE TABLE TS21_01.SUP_ORD AS SELECT SUPPLIERS.SUPPLIER_ID, SUPPLIERS.SUPPLIER_NAME, ORDERS.ORDER_NUMBER  
FROM TS21_01.SUPPLIERS  
LEFT OUTER JOIN TS21_01.ORDERS  
ON SUPPLIERS.SUPPLIER_ID = ORDERS.SUPPLIER_ID;