CREATE TABLE TS15_01.SUPPLIERS
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS15_01.SUPPLIERS1
(
SUPPLIER_ID1 NUMBER(10),
SUPPLIER_NAME1 VARCHAR2(20),
SUPPLIER_ADDRESS1 VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS15_01.INSERT_SUPP     
IS    
BEGIN    
INSERT INTO TS15_01.SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME,SUPPLIER_ADDRESS) 
SELECT S1.SUPPLIER_ID1, S1.SUPPLIER_NAME1, S1.SUPPLIER_ADDRESS1 FROM TS15_01.SUPPLIERS1 S1;    
END;    
/

EXECUTE TS15_01.INSERT_SUPP;
