CREATE TABLE TS01_02.STUDENTS1
(
STUDENT_ID NUMBER(5) NOT NULL,
STUDENT_NAME VARCHAR2(20),
GROUP_ID FLOAT(5),
GROUP_ID1 BINARY_FLOAT,
GROUP_ID2 BINARY_DOUBLE,
GROUP_ID3 FLOAT(5),
ADDRESS1 CHAR(5),
ADDRESS2 NCHAR(5),
ADDRESS3 NVARCHAR2(5),
PHOTO1 LONG,
PHOTO4 BFILE,
PHOTO5 BLOB,
PHOTO6 CLOB,
PHOTO7 NCLOB,
AGE NUMBER(2),
DOB DATE,
DOJ1 TIMESTAMP
);

CREATE OR REPLACE PROCEDURE TS01_02.Create_Tab_STU2_TS01 
IS
BEGIN

CREATE TABLE TS01_02.STUDENTS2 AS SELECT 
S1.STUDENT_ID,
S1.STUDENT_NAME,
S1.GROUP_ID,
S1.GROUP_ID1,
S1.GROUP_ID2,
S1.GROUP_ID3,
S1.ADDRESS1,
S1.ADDRESS2,
S1.ADDRESS3
FROM TS01_02.STUDENTS1 S1;

END;
/