CREATE TABLE TS25_01.SUPPLIERS
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS25_01.CREATE_TAB_SUP_ORD1 
IS
BEGIN

CREATE TABLE TS25_01.SUP_ORD AS SELECT S1.SUPPLIER_ID, S2.SUPPLIER_NAME 
FROM TS25_01.SUPPLIERS S1,TS25_01.SUPPLIERS S2 WHERE S1.SUPPLIER_ID < S2.SUPPLIER_NAME;

END;
/